Repository redhat-beyond/Xpense, pull requests merged in 2022-03, with the labels that each got.

#26 Init house app
  Xpense/settings.py
  house/admin.py
  house/apps.py
  house/init.py
  house/migrations/__init__.py
  house/models.py
  house/tests.py
  house/views.py
Labels: Waiting on contributor

#31 Added ERD
  Xpense_ERD.png
Labels: Ready for a review

#23 Expenses: add category choice filed to the expenses model with init options
  Pipfile
  Pipfile.lock
  expenses/admin.py
  expenses/models.py
Labels: Ready to merge, Ready for a review

#36 Pipeline: add tests to the Github action
  .github/workflows/tests.yml
  Pipfile
  Pipfile.lock
  pytest.ini
Labels: Waiting on contributor

#28 🏗️ House: creating models and migrations
  house/admin.py
  house/migrations/0001_initial.py
  house/migrations/0002_add_initial_data.py
  house/models.py
Labels: Ready to merge

#41 General: Add Vscode configuration to gitignore
  .gitignore
Labels: Ready for a review
