Repository redhat-beyond/Xpense, pull requests merged in 2022-04, with the labels that each got.

#46 Xpense: Updating ERD with Tips
  Xpense_ERD.png
Labels: Ready for a review

#42 Expense app: Update expense up
  expenses/migrations/0001_initial.py
  expenses/migrations/0002_alter_expenses_date.py
  expenses/models.py
  expenses/test/test_expenses.py
  expenses/tests.py
  house/__init__.py
  house/migrations/0001_initial.py
  house/tests/house_tests.py
Labels: Ready to merge

#53 Pipefile: lock installed modules in pipefile
  Pipfile
  Pipfile.lock
Labels: Ready to merge

#56 Main: remove "main" app from are project
  Xpense/settings.py
  Xpense/urls.py
  main/__init__.py
  main/admin.py
  main/apps.py
  main/migrations/__init__.py
  main/models.py
  main/templates/main/index.html
  main/tests.py
  main/views.py
Labels: Ready for a review

#50 Expeses: add description field to the expenses model
  .github/workflows/flake8.yml
  expenses/migrations/0001_initial.py
  expenses/migrations/0002_alter_expenses_date.py
  expenses/models.py
Labels: Ready to merge

#60 Data Mock: Add scripts to create mock data for our project
  Pipfile
  Pipfile.lock
  Xpense/settings.py
  factories/__init__.py
  factories/house.py
  scripts/__init__.py
  scripts/create_mock_data.py
Labels: Waiting on contributor

#52 House: Add house description
  expenses/migrations/0001_initial.py
  house/migrations/0001_initial.py
  house/models.py
Labels: Ready to merge

#63 Expenses: Fix date variable in expenses.models
  expenses/migrations/0001_initial.py
  expenses/models.py
Labels: Ready to merge

#62 Data Mock: Add Expense mock data creation script
  Pipfile.lock
  factories/expense.py
  scripts/create_mock_data.py
  test.py
Labels: Waiting on contributor, Ready to merge

#55 Routing: Init routing the routing for the dashboard and the house view and form
  Xpense/urls.py
  house/urls.py
  house/views.py
Labels: Waiting on contributor, Ready to merge

#66 Mock Data: expenses mock data small fix
  factories/expense.py
Labels: Ready for a review

#58 General: creating the base and home html
  Xpense/settings.py
  house/constants.py
  house/views.py
  static/css/app_layout.css
  templates/base.html
  templates/home.html
Labels: Ready to merge

#64 General: linting and organizing
  Xpense/settings.py
  expenses/models.py
  factories/house.py
Labels: Ready for a review

#67 Global Page: Create global page
  house/constants.py
  house/views.py
  static/css/global.css
  templates/global/global.html
Labels: Ready for a review

#38 Xpense: Adding DFD
  Xpense_DFD.png
Labels: Ready to merge

#75 Global Page: Initializing the sidebar and table
  house/views.py
  static/css/global.css
  templates/global/filter_form.html
  templates/global/global.html
  templates/global/sidebar.html
  templates/global/table.html
Labels: Ready to merge, Ready for a review

#76 Global page: Add Global page charts
  expenses/models.py
  expenses/test/test_expenses.py
  house/views.py
  static/css/chart.css
  static/css/global.css
  templates/global/chart.html
  templates/global/global.html
  tests/__init__.py
  tests/global_page_tests.py
Labels: Ready for a review

#81 Global Page: Add Global page filter form and filter logic
  house/constants.py
  house/forms.py
  house/helpers.py
  house/tests/house_tests.py
  house/urls.py
  house/views.py
  static/css/form.css
  static/css/sidebar.css
  templates/global/city_dropdown.html
  templates/global/filter_form.html
  templates/global/sidebar.html
Labels: Ready to merge

#71 Tips views: create views for tips app
  Xpense/urls.py
  static/css/tips_board.css
  templates/base.html
  templates/tips/add_tip.html
  templates/tips/board.html
  templates/tips/edit_tip.html
  tips/constants.py
  tips/forms.py
  tips/tests/tips_views_tests.py
  tips/urls.py
  tips/views.py
Labels: Waiting on contributor, Ready to merge

#80 House: Adding the Login Page
  house/constants.py
  house/forms.py
  house/tests/house_login_page_tests.py
  house/urls.py
  house/views.py
  static/css/login.css
  templates/base.html
  templates/login/login.html
Labels: Ready to merge, Ready for a review

#72 Mine page: Create views and templates
  Xpense/urls.py
  expenses/test/test_expenses.py
  factories/house.py
  house/constants.py
  house/tests/house_tests.py
  house/urls.py
  house/views.py
  static/css/mine_house_and_expenses.css
  templates/house_view/expenses_table.html
  templates/house_view/house_table.html
  templates/house_view/house_table_title.html
  templates/house_view/mine_page.html
  templates/house_view/sidebar.html
Labels: Ready to merge
