Repository redhat-beyond/Xpense, pull requests merged in 2022-05, with the labels that each got.

#106 User Authntication: Add user authentication base on django authentication
  Pipfile
  Pipfile.lock
  Xpense/settings.py
  Xpense/urls.py
  accounts/__init__.py
  accounts/admin.py
  accounts/apps.py
  accounts/migrations/__init__.py
  accounts/models.py
  accounts/tests/__init__.py
  accounts/tests/tests.py
  accounts/urls.py
  accounts/views.py
  house/constants.py
  house/urls.py
  house/views.py
  static/css/accounts/login.css
  static/css/accounts/signup.css
  templates/base.html
  templates/registration/login.html
  templates/registration/signup.html
Labels: Waiting on contributor, Ready for a review

#113 House Filter: refactor profession filtering
  house/helpers.py
  tests/house_tests.py
Labels: Waiting on contributor, Ready for a review

#109 Tests: Adjust views and form tests to use Django's client
  tests/conftest.py
  tests/global_page_tests.py
  tests/house_login_page_tests.py
  tests/house_tests.py
  tests/tips_views_tests.py
Labels: Waiting on contributor, Need to resolve conflicts

#110 UI: Updating and Fixing the UI
  Pipfile
  Pipfile.lock
  Xpense/settings.py
  Xpense/urls.py
  static/css/app_layout.css
  static/css/chart.css
  static/css/form.css
  static/css/global.css
  static/css/sidebar.css
  static/css/tips_board.css
  static/images/ico.png
  templates/base.html
  templates/global/chart.html
  templates/global/filter_form.html
  templates/global/global.html
  templates/global/table.html
Labels: Ready to merge, Ready for a review

#120 Tests: Fix flakey test duo to not specified profession for other parent
  tests/house_tests.py
Labels: Ready to merge

#112 Filter Form: Income range visual update
  static/css/app_layout.css
  static/css/form.css
  static/css/sidebar.css
  templates/global/filter_form.html
Labels: Ready to merge

#117 House: Filter only public houses to show on global page
  factories/house.py
  house/helpers.py
  house/views.py
  tests/global_page_tests.py
  tests/house_tests.py
Labels: Ready to merge

#118 Chart: exported chart logic to external file
  static/js/bar_chart.js
  static/js/pie_chart.js
  static/js/random_colors.js
  templates/global/chart.html
  templates/tips/add_tip.html
  templates/tips/edit_tip.html
Labels: Ready to merge

#111 Auth: attach house model to django user
  expenses/models.py
  factories/house.py
  factories/tests.py
  factories/user.py
  house/constants.py
  house/forms.py
  house/migrations/0001_initial.py
  house/models.py
  house/urls.py
  house/views.py
  scripts/create_mock_data.py
  scripts/tests.py
  static/css/house_create.css
  static/css/login.css
  templates/base.html
  templates/house_view/house_create.html
  templates/login/login.html
  tests/accounts_tests.py
  tests/conftest.py
  tests/const.py
  tests/global_page_tests.py
  tests/house_login_page_tests.py
  tests/house_tests.py
  tests/test_expenses.py
  tests/test_house_creation.py
Labels: Ready to merge

#132 Charts: refactored the use of charts from the js files
  static/js/bar_chart.js
  static/js/pie_chart.js
  templates/global/chart.html
Labels: Ready to merge

#128 Xpense: Updating ERD
  Xpense_ERD.png
Labels: Ready for a review

#129 Xpense: Updating DFD
  Xpense_DFD.png
Labels: Ready for a review

#133 House: Chaining the models City Country
  Pipfile
  Pipfile.lock
  Xpense/settings.py
  Xpense/urls.py
  expenses/migrations/0001_initial.py
  factories/house.py
  house/constants.py
  house/fixtures/countries_cities.json
  house/forms.py
  house/migrations/0001_initial.py
  house/migrations/0002_add_initial_data.py
  house/migrations/0002_loaddata.py
  house/models.py
  house/urls.py
  house/views.py
  scripts/countries_cities_data.json
  scripts/load_countries_cities.py
  static/css/app_layout.css
  static/css/form.css
  templates/global/city_dropdown.html
  templates/global/filter_form.html
  templates/house_view/house_create.html
  tests/conftest.py
  tests/house_tests.py
  tests/test_expenses.py
Labels: Ready to merge

#134 Formatting: format code and create pre-commit that format code automatically
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  README.md
  Xpense/settings.py
  Xpense/urls.py
  accounts/urls.py
  accounts/views.py
  expenses/models.py
  expenses/tests.py
  factories/expense.py
  factories/user.py
  house/models.py
  house/tests.py
  house/views.py
  manage.py
  scripts/create_mock_data.py
  scripts/load_countries_cities.py
  static/css/chart.css
  static/css/global.css
  templates/global/chart.html
  templates/global/filter_form.html
  templates/tips/edit_tip.html
  tests/accounts_tests.py
  tests/conftest.py
  tests/const.py
  tests/global_page_tests.py
  tests/house_tests.py
  tests/test_house_creation.py
  tests/tips_views_tests.py
  tips/models.py
  tips/views.py
Labels: Ready to merge, Ready for a review

#136 Vagrant: Add git install command
  setup.sh
Labels: Ready to merge

#83 Mine page: add the option to add expense
  .gitignore
  expenses/migrations/0001_initial.py
  expenses/models.py
  house/constants.py
  house/forms.py
  house/models.py
  house/urls.py
  house/views.py
  static/css/mine.css
  static/css/mine_house_and_expenses.css
  templates/house_view/add_expense.html
  templates/house_view/house_table.html
  templates/house_view/house_table_title.html
  templates/house_view/mine_page.html
  templates/house_view/sidebar.html
  tests/conftest.py
  tests/const.py
  tests/house_tests.py
  tests/my_house_tests.py
  tests/test_expenses.py
Labels: Ready to merge

#123 Mine page: add the option to edit and delete expense
  .gitignore
  expenses/migrations/0001_initial.py
  house/constants.py
  house/urls.py
  house/views.py
  templates/house_view/edit_expense.html
  templates/house_view/expenses_table.html
  tests/const.py
  tests/my_house_tests.py
  tests/test_expenses.py
Labels: Waiting on contributor, Ready for a review

#139 Home Page: Create a smooth scrolling home page
  house/constants.py
  static/css/home.css
  static/js/home.js
  templates/home.html
  templates/home/home.html
Labels: Ready to merge

#127 Mine Page: Adding Charts Display of the Expenses
  house/constants.py
  house/forms.py
  house/views.py
  static/css/app_layout.css
  static/css/form.css
  static/css/house_create.css
  static/css/mine.css
  templates/house_view/mine_chart.html
  templates/house_view/mine_page.html
  tests/my_house_tests.py
Labels: Ready to merge

#137 Mine Page: Add the option to edit house after creation
  house/constants.py
  house/urls.py
  house/views.py
  templates/house_view/edit_house.html
  templates/house_view/house_table.html
  tests/const.py
  tests/house_tests.py
  tests/my_house_tests.py
Labels: Ready to merge, Ready for a review

#140 House: Fix edit house form
  templates/house_view/edit_house.html
Labels: Ready to merge
